### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by muhammadfaizan** [vkarpov15/kareem#6] opened 2016-09-02 13:16 UTC
I am getting this error, while making a query

`RangeError: Maximum call stack size exceeded
    at H:\Products\remedy-now-server\db-handle\node_modules\mongoose\node_modules\kareem\index.js:156:57
    at H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\query.js:1048:23
    at next (H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\model.js:2480:14)
    at next (H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\model.js:2646:21)
    at H:\Products\remedy-now-server\db-handle\node_modules\mongoose\node_modules\kareem\index.js:160:11
    at H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\query.js:1048:23
    at next (H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\model.js:2480:14)
    at next (H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\model.js:2646:21)
    at H:\Products\remedy-now-server\db-handle\node_modules\mongoose\node_modules\kareem\index.js:160:11
    at H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\query.js:1048:23
    at next (H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\model.js:2480:14)
    at next (H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\model.js:2646:21)
    at H:\Products\remedy-now-server\db-handle\node_modules\mongoose\node_modules\kareem\index.js:160:11
    at H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\query.js:1048:23
    at next (H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\model.js:2480:14)
    at next (H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\model.js:2646:21)
    at H:\Products\remedy-now-server\db-handle\node_modules\mongoose\node_modules\kareem\index.js:160:11
    at H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\query.js:1048:23
    at next (H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\model.js:2480:14)
    at next (H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\model.js:2646:21)
    at H:\Products\remedy-now-server\db-handle\node_modules\mongoose\node_modules\kareem\index.js:160:11
    at H:\Products\remedy-now-server\db-handle\node_modules\mongoose\lib\query.js:1048:23`

**Comment by markstos** [comment] 2017-12-27 03:25
I'm also getting "RangeError: Maximum call stack size exceeded" that appears to trace back to this module, but I'm not yet clear what the root cause is.

**Comment by vkarpov15** [comment] 2018-01-03 17:42
@markstos @muhammadfaizan can you tell me what version of mongoose you're using (and @markstos can you provide a stack trace)? Otherwise I'm just taking shots in the dark

**Comment by markstos** [comment] 2018-01-03 17:52
@vkarpov15 My best guess is that I ran into a variant of https://github.com/Automattic/mongoose/issues/4046 and it just happened to mention `kareem` in the stack trace, but Kareem was not fault. Our code has since changed and I can't produce the stack trace or a repro case now, sorry.

**Comment by vkarpov15** [comment] 2018-01-03 21:14
In which case I'll close this for now, will re-open if I can get some more info.

**Closed by vkarpov15** 2018-01-03 21:14 UTC
